#!/usr/bin/env bash
# Scaffolds the two files needed to onboard a new iCEDQ service into this
# compose stack: application-local-compose-<service>.yaml (a placeholder to
# fill in from the service's real application-dev.yaml) and run-<service>.sh
# (a working script, no edits usually needed beyond the port/profiles line).
#
# This does NOT fully automate onboarding — see the icedq-onboard-service
# skill (icedq-smoke/.claude/skills/icedq-onboard-service/SKILL.md) for the
# full procedure, including where to find the real dev-profile config to copy
# from, which schemas to add to init-db.sql, and how to read crash logs.
#
# Usage: ./onboard-service.sh <service-name> <port> [main-schema]
# Example: ./onboard-service.sh datawarehouse 9170 dqw

set -euo pipefail

SERVICE="${1:?usage: $0 <service-name> <port> [main-schema]}"
PORT="${2:?usage: $0 <service-name> <port> [main-schema]}"
SCHEMA="${3:-$SERVICE}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

YAML="$SCRIPT_DIR/application-local-compose-$SERVICE.yaml"
RUN="$SCRIPT_DIR/run-$SERVICE.sh"

if [ -e "$YAML" ] || [ -e "$RUN" ]; then
  echo "Refusing to overwrite existing files for '$SERVICE'. Remove them first if you really want to regenerate." >&2
  exit 1
fi

cat > "$YAML" <<EOF
# TODO: derive this from <service-repo>/src/main/resources/application-dev*.yaml
# See the icedq-onboard-service skill for the full checklist. Key swaps:
#   - every remote hostname -> compose service name (postgres/rabbitmq/vault/keycloak/temporal)
#   - spring.cloud.vault.authentication: APPROLE -> TOKEN, token: root
#   - spring.datasource -> postgres:5432/icedq_db, dbAdmin/devpassword
#   - spring.rabbitmq -> rabbitmq:5672, rabbitmq/rabbitmq
#   - outbound base-url for services IN this stack (run-*.sh exists): http://icedq-<name>-smoke:<port>
#   - outbound base-url for services NOT in stack (boot-only, lazy): http://localhost:1
#   - NEVER use localhost:<port> inside container yamls for peer services (use icedq-*-smoke)
#   - NEVER SQL-backfill operational data between schemas (no sync scripts)
#   - init-db.sql: CREATE SCHEMA only — no stub tables for other services' Liquibase
---
spring:
  cloud:
    vault:
      uri: http://vault:8200
      enabled: true
      authentication: TOKEN
      token: root
  datasource:
    url: jdbc:postgresql://postgres:5432/icedq_db
    driver: org.postgresql.Driver
    username: dbAdmin
    password: devpassword

icedq:
  security:
    oidc:
      base-url: http://keycloak:8080
      auth-url: \${icedq.security.oidc.base-url}/auth

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
EOF

cat > "$RUN" <<EOF
#!/usr/bin/env bash
# Runs a freshly built $SERVICE image against the compose dependency stack
# and smoke-tests it. Generated by onboard-service.sh — same pattern as
# run-admin.sh/run-connection.sh/run-workflow.sh.
#
# Usage:
#   docker compose up -d      # bring up deps first
#   ./run-$SERVICE.sh <image:tag>

set -euo pipefail

IMAGE="\${1:?usage: \$0 <image:tag>}"
NETWORK="icedq-smoke-deps_default"
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
NAME="icedq-${SERVICE}-smoke"

docker rm -f "\$NAME" >/dev/null 2>&1 || true

echo "[run-$SERVICE] Starting \$IMAGE against the compose stack..."
docker run -d --name "\$NAME" \\
  --network "\$NETWORK" \\
  -p $PORT:$PORT \\
  -v "\$SCRIPT_DIR/application-local-compose-$SERVICE.yaml:/app/extra-config/application-local-compose-$SERVICE.yaml:ro" \\
  -v "\$SCRIPT_DIR/icedq-datatypes.json:/app/config/icedq-datatypes.json:ro" \\
  -e EXTRA_CLASSPATH=/app/extra-config \\
  -e SPRING_PROFILES_ACTIVE=smi,smi-hcp,dev,local-compose-$SERVICE \\
  -e SERVER_SSL_ENABLE=false \\
  -e OTEL_JAVAAGENT_ENABLED=false \\
  "\$IMAGE"

echo "[run-$SERVICE] Waiting for it to boot (Spring Boot cold start, ~30-60s)..."
n=0
until [ "\$n" -ge 60 ]; do
  health=\$(curl -sk --max-time 3 http://localhost:$PORT/actuator/health 2>/dev/null || echo '{}')
  db_status=\$(echo "\$health" | python3 -c "import json,sys; print(json.load(sys.stdin).get('components',{}).get('db',{}).get('status','?'))" 2>/dev/null || echo '?')
  if [ "\$db_status" = "UP" ]; then
    echo "[run-$SERVICE] PASS — $SERVICE is alive, db reachable. Full health:"
    echo "\$health" | python3 -m json.tool 2>/dev/null || echo "\$health"
    exit 0
  fi
  if ! docker ps --format '{{.Names}}' | grep -qx "\$NAME"; then
    echo "[run-$SERVICE] Container exited. Logs:" >&2
    docker logs "\$NAME" 2>&1 | tail -60 >&2
    exit 1
  fi
  sleep 2
  n=\$((n+1))
done

echo "[run-$SERVICE] Timed out waiting for db to come up healthy. Last logs:" >&2
docker logs "\$NAME" 2>&1 | tail -60 >&2
exit 1
EOF
chmod +x "$RUN"

echo "Scaffolded:"
echo "  $YAML  (edit this — currently a bare placeholder)"
echo "  $RUN   (usually needs no edits beyond what onboard-service.sh already filled in)"
echo ""
echo "Next:"
echo "  1. Add '$SCHEMA' (and any other schemas) to init-db.sql — CREATE SCHEMA only, no stub tables"
echo "  2. docker compose up -d --force-recreate postgres"
echo "  3. Edit $YAML from the service's real application-dev*.yaml (see skill Step 3)"
echo "  4. bash $RUN <image:tag>   # boot smoke"
echo "  5. If E2E: wire peer outbound URLs to icedq-*-smoke, add api-gateway routes, run smoke.mjs via :9080"
echo ""
echo "Full checklist: .claude/skills/icedq-onboard-service/SKILL.md"
